# Generated by Django 5.2.4 on 2025-09-16 14:31

import django.contrib.auth.models
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_clientes/')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('barrio', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_cliente', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='Natural', max_length=10)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'Número de Identificación Tributaria'), ('PAS', 'Pasaporte')], default='CC', max_length=3)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('metodo_pago_preferido', models.CharField(blank=True, choices=[('transferencia', 'Transferencia Bancaria'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('tarjeta', 'Tarjeta de crédito/débito'), ('efectivo', 'Efectivo')], max_length=30, null=True)),
                ('informacion_facturacion', models.TextField(blank=True, null=True)),
                ('estado_verificacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('verificado', 'Verificado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('documento_rut', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('documento_cedula', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('contrato_firmado', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('estudio_credito', models.FileField(blank=True, help_text='Documento del estudio de crédito del cliente', null=True, upload_to='estudios_credito/', verbose_name='Estudio de crédito')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('moroso', models.BooleanField(default=False)),
                ('fecha_marcado_moroso', models.DateField(blank=True, null=True)),
                ('dias_mora', models.IntegerField(default=0)),
                ('deuda_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('estado_usuario', models.CharField(default='activo', max_length=20, verbose_name='Estado')),
                ('ultimo_acceso', models.DateTimeField(auto_now=True, verbose_name='Último acceso')),
                ('activation_token', models.CharField(blank=True, max_length=50, null=True, verbose_name='Token de activación')),
                ('activation_token_created', models.DateTimeField(blank=True, null=True, verbose_name='Fecha creación token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acceso administración')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alquiler.cliente', verbose_name='Cliente asociado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='alquiler.rol', verbose_name='Rol asignado')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre_usuario'],
            },
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado_alquiler', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('reservado', 'Reservado'), ('pendiente_aprobacion', 'Pendiente de Aprobación')], default='pendiente_aprobacion', max_length=20)),
                ('renovacion', models.BooleanField(default=False)),
                ('aprobado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('contrato_firmado', models.BooleanField(default=False)),
                ('con_iva', models.BooleanField(default=False)),
                ('renovacion_automatica', models.BooleanField(default=False)),
                ('numero_factura', models.CharField(blank=True, help_text='Dejar en blanco para reservas', max_length=20, null=True, unique=True)),
                ('es_reserva', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='alquiler.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('entrega', 'Acta de Entrega'), ('devolucion', 'Acta de Devolución')], max_length=10)),
                ('archivo', models.FileField(upload_to='actas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('numero_acta', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='alquiler.alquiler')),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('firma_cliente', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('firma_representante', models.ImageField(blank=True, null=True, upload_to='firmas_representante/')),
                ('documento_contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('terminos_contrato', models.TextField(blank=True, null=True)),
                ('alquiler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='alquiler.alquiler')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, help_text='Código único de identificación del equipo', max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie', models.TextField(blank=True, help_text='Ingrese múltiples números de serie separados por comas', null=True, verbose_name='Números de serie')),
                ('requiere_serie', models.BooleanField(default=True, verbose_name='Requiere número de serie')),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('alquilado', 'En alquiler'), ('reservado', 'Reservado'), ('mantenimiento', 'En mantenimiento')], default='disponible', max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('cantidad_total', models.PositiveIntegerField(default=1)),
                ('cantidad_disponible', models.PositiveIntegerField(default=1)),
                ('precio_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_semana', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_trimestre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_semestre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_anio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_ultimo_alquiler', models.DateField(blank=True, null=True)),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('es_html', models.BooleanField(default=False)),
                ('valoracion_promedio', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['marca', 'modelo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valoracion_promedio__gte', 0.0), ('valoracion_promedio__lte', 5.0)), name='valoracion_promedio_rango'), models.CheckConstraint(condition=models.Q(('cantidad_disponible__lte', models.F('cantidad_total'))), name='cantidad_disponible_no_mayor_total'), models.CheckConstraint(condition=models.Q(('precio_dia__gte', 0)), name='precio_dia_positivo'), models.CheckConstraint(condition=models.Q(('cantidad_total__gte', 0)), name='cantidad_total_positiva')],
            },
        ),
        migrations.CreateModel(
            name='DetalleAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros_serie', models.JSONField(blank=True, default=list, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('periodo_alquiler', models.CharField(choices=[('dia', 'Por día'), ('semana', 'Por semana'), ('mes', 'Por mes'), ('trimestre', 'Por trimestre'), ('semestre', 'Por semestre'), ('anio', 'Por año')], default='dia', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('con_iva', models.BooleanField(default=True, verbose_name='Aplica IVA')),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='alquiler.alquiler')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alquiler.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='FotoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, help_text='Suba una foto del equipo', null=True, upload_to='fotos_equipos/', verbose_name='Archivo de imagen')),
                ('es_principal', models.BooleanField(default=False, help_text='Marcar si esta es la foto principal del equipo', verbose_name='Foto principal')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='alquiler.equipo', verbose_name='Equipo asociado')),
            ],
            options={
                'verbose_name': 'Foto de equipo',
                'verbose_name_plural': 'Fotos de equipos',
                'ordering': ['-es_principal', 'fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('transferencia', 'Transferencia bancaria'), ('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('otros', 'Otro método electrónico')], max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Parcial'), ('vencido', 'Vencido'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('factura_generada', models.BooleanField(default=False)),
                ('referencia_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('notas', models.TextField(blank=True, null=True)),
                ('alquiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='alquiler.alquiler')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='UnidadEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='alquiler.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Inicio de sesión'), ('login_failed', 'Intento fallido de login'), ('logout', 'Cierre de sesión'), ('password_change', 'Cambio de contraseña'), ('password_reset', 'Restablecimiento de contraseña'), ('user_edit', 'Edición de perfil'), ('user_create', 'Creación de usuario'), ('user_delete', 'Eliminación de usuario'), ('role_change', 'Cambio de rol'), ('status_change', 'Cambio de estado'), ('permission_change', 'Cambio de permisos'), ('data_access', 'Acceso a datos sensibles'), ('config_change', 'Cambio de configuración'), ('export_data', 'Exportación de datos'), ('admin_action', 'Acción administrativa')], max_length=50, verbose_name='Acción')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Agente de usuario')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Detalles')),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('warning', 'Advertencia')], default='success', max_length=20, verbose_name='Estado')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_by_actions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario objetivo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='alquiler_us_timesta_e6fe31_idx'), models.Index(fields=['user', 'timestamp'], name='alquiler_us_user_id_c725eb_idx'), models.Index(fields=['action', 'status'], name='alquiler_us_action_648ea2_idx')],
            },
        ),
    ]
